### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by capturingfoxes** [capturingfoxes/pastel#1]
## Daemon
* [ ] GraphQL API for configuring daemon & querying library data
* [ ] Scheduled tasks
* [ ] Library scanner
* [ ] External metadata fetcher
* [ ] Tagging capabilities (including automated)
* [ ] Image thumbnailing
* [ ] File serving
* [ ] Permission concepts of "library admin" and "daemon admin"

## Command Line Interface
* [ ] User creation & auth generation (API key generation)
* [ ] Tagging
* [ ] Querying & searching for library data

## Frontend

**Comment by raindrop1** [comment]
2019-01-12 TODO
- [ ] fix user schema
- [ ] revise metadata fields

**Comment by raindrop1** [comment]
2019-01-06 TODO
- [ ] Add release type to pastel_tags
- [ ] Incorporate release type into albums as an Enum
- [ ] "Loose" track album type?

**Comment by raindrop1** [comment]
Don't base64 the global IDs in GQL API

**Comment by raindrop1** [comment]
- [ ] Configurable RDBMS choice

**Comment by raindrop1** [comment]
- [ ] User ID field in collection contributions? No support for association proxy makes this difficult.

**Comment by raindrop1** [comment]
* [ ] Standardize all FK mutation inputs to be base64 relay IDs

**Comment by raindrop1** [comment]
* [ ] Provide GQL endpoints for ambiguity objects
* [ ] Genre relationships
* [ ] Authorization for APIKey and User resolving

**Comment by raindrop1** [comment]
* [ ] Combined decorator for the GraphQL mutations

**Comment by raindrop1** [comment]
* [ ] turn instances of `label` or `labels` into `recordLabel` and `recordLabels` to prevent ambiguity

**Comment by raindrop1** [comment]
"Private" playlists, i.e. user-specific and hidden from everyone else

**Comment by raindrop1** [comment]
* [ ] https://pre-commit.com/ for lint checks

**Comment by raindrop1** [comment]
* [ ] How to handle deletions of empty Artists / Albums?
* [ ] Check ON DELETE cascades and add where appropriate (e.g. editions should cascade on album deletion)
* [ ] Add event logging checks to bottom of the mutation tests

**Comment by raindrop1** [comment]
* [ ] Add _deleted_ column to some tables and create resolvers that filter those out. Use them for internal comparisons, e.g. logging, and resurrection.
